[book]
title = "Chia Mempool: Generalized Fast Forward"
authors = ["Richard Kiss"]
language = "en"
src = "src"

[output.html]
additional-js = ["giscus.js"]
default-theme = "light"
preferred-dark-theme = "navy"
